### ISSUE TITLE
Add a delete_file command to the interface

### ISSUE THREAD

**Issue by fpoms** [scanner-research/storehouse#1]
Storehouse currently only supports creating new files and not deleting them. We should support some way to remove individual files and/or groups of files (some backends, like GCS, allow you to perform mass background deletions by setting 'lifecycle' rules https://cloud.google.com/storage/docs/managing-lifecycles).

**Comment by fpoms** [comment]
@willcrichton Closed now?

**Comment by willcrichton** [comment]
Yeah. I'll leave it to @satyaprateek1994 to fill in the S3 bindings.
