### ISSUE TITLE
ImportError: cannot import name 'StorageConfig'

### ISSUE THREAD

**Issue by wangyongjie-ntu** [scanner-research/storehouse#4]
I have installed storehouse as 'pip install storehouse'
when I execute this command ' from scannerpy import Job'
it returned this error "ImportError: cannot import name 'StorageConfi' "

How can i fix it?

**Comment by willcrichton** [comment]
Hi, we don't actually recommend you install storehouse through pip. You should follow the installation instructions in Scanner: http://scanner.run/installation.html
